version: "3"
services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=local_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d